# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d94e28e0497829a7c850804a474b312afd68c6161520f7bbbbde6e2a8fe0e3ae04c9777f6269cd22bd434ce07b29df17588d02326321c2d86d035df25df63429

test:
  secret_key_base: ed1c439b45e3125eecd7a42ef8d70225f4600d5116491b7ab746289351eff2328bc3969bdd3928300684f6ce5a2a5b77f18ab2a9e458f17bf72bfae3b0d2f04a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
